[package]
name = "great-theorems"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["Johann Birnick <https://jbirnick.net>"]
license = "MIT"
description = "Theorem/Proof environments. Straightforward, functional, clean."
repository = "https://github.com/jbirnick/typst-great-theorems"
keywords = ["theorem", "proof", "math", "mathematics"]
categories = ["components", "model"]
disciplines = ["mathematics", "computer-science", "physics", "engineering", "philosophy", "education"]
exclude = ["examples", "build"]
